package com.awesome.financial.control.afc.dto;

import static org.assertj.core.api.Assertions.assertThat;

import java.math.BigDecimal;
import java.util.Collections;
import org.junit.jupiter.api.Test;

public class DtoCoverageTest {

    @Test
    void testBrapiQuoteResponse() {
        var fundamental =
                new BrapiQuoteResponse.BrapiFundamental(
                        BigDecimal.ONE,
                        BigDecimal.TEN,
                        BigDecimal.ZERO,
                        BigDecimal.ONE,
                        BigDecimal.ONE);
        var result =
                new BrapiQuoteResponse.BrapiQuoteResult(
                        "TICKER",
                        "Name",
                        "Long Name",
                        "BRL",
                        BigDecimal.ONE,
                        BigDecimal.ZERO,
                        BigDecimal.ZERO,
                        "url",
                        fundamental);
        var response = new BrapiQuoteResponse(Collections.singletonList(result), "now");

        assertThat(response.results()).hasSize(1);
        assertThat(response.requestedAt()).isEqualTo("now");
        assertThat(result.symbol()).isEqualTo("TICKER");
        assertThat(fundamental.dividendYield()).isEqualTo(BigDecimal.ONE);

        // Touch autogenerated methods
        assertThat(response.toString()).isNotNull();
        assertThat(response.hashCode()).isNotZero();
        assertThat(response.equals(response)).isTrue();
    }
}
